import { AboutSlint, VerticalBox, Button, ScrollView, Palette, HorizontalBox, ComboBox, CheckBox, LineEdit } from "std-widgets.slint";

export component FirstRunPage inherits VerticalBox
{
    callback set_page(int);
    callback restore_with_system();

    Rectangle {}
    Text {
        text: @tr("FirstRunPage@pipes-doesnt-persist.msg");
            horizontal-alignment: center;
    }
    Text {
        text: @tr("FirstRunPage@ask-restore-pipes.msg");
        horizontal-alignment: center;
        font-weight: 700;
    }
    HorizontalBox {
        Rectangle {}
        Button {
            text: @tr("FirstRunPage@decline.btn");
            clicked => {
                set_page(0);
            }
        }
        Button {
            text: @tr("FirstRunPage@confirm.btn");
            clicked => {
                restore_with_system();
            }
        }
        Rectangle {}
    }
    Text {
        text: @tr("FirstRunPage@can-be-changed-later.msg");
        opacity: 0.5;
        horizontal-alignment: center;
    }
    Rectangle {}
    Text {
        text: @tr("FirstRunPage@manual-autostart.msg");
        opacity: 0.5;
        horizontal-alignment: center;
    }
}