import { AboutSlint, VerticalBox, Palette, HorizontalBox, Button, CheckBox, ScrollView, LineEdit } from "std-widgets.slint";
import { Pipe } from "../structs.slint";
import { LabelBox } from "../assets.slint";

export component PipeList inherits Rectangle {
    in property <[Pipe]> pipes;
    callback new_pipe();
    callback edt_pipe(Pipe);

    // Pipe list //
    VerticalLayout {
        ScrollView {
        mouse-drag-pan-enabled: true;
            VerticalBox {
                for pipe in pipes: TouchArea {
                    HorizontalBox {   
                        LabelBox {
                            text: pipe.sink;
                        }
                        
                        Text {
                            width: self.min-width;
                            text: "→";

                            horizontal-alignment: center;
                            vertical-alignment: center;
                        }

                        LabelBox {
                            text: pipe.source;
                        }
                        
                    }
                    clicked => {
                        edt_pipe(pipe)
                    }
                }
                Rectangle {
                    if pipes.length == 0: Text {
                        text: "Create a new pipe using the\n"
                             +"button below on the right.";
                        horizontal-alignment: center;
                        vertical-alignment: center;
                    }
                    
                }
            }
        }



        // Bottom bar //
        Rectangle {
            height: 1px;
            background: Palette.border;
        }
        Rectangle {
            height: self.min-height;
            background: Palette.control-background;
            HorizontalBox {
                /*
                CheckBox {
                    text: "Restore pipes after reboot.";
                    changed checked => {

                    }
                }
                */
                Rectangle {}
                Button {
                    width: self.min-width;
                    text: "Create pipe";
                    clicked => {
                        new_pipe()
                    }
                }
            }
        }
    }
}