import { AboutSlint, VerticalBox, HorizontalBox } from "std-widgets.slint";

import { MainPage }     from "components/00.MainPage/MainPage.slint";
import { SettingsPage } from "components/01.SettingsPage/SettingsPage.slint";

import { Pipe } from "structs.slint";


export component MainWindow inherits Window
{
    // Window Properties //
    title: "VirtualPipe";
    min-width  : 600px;
    min-height : 300px;

    // Properties //
    in-out property <[Pipe]> pipelist: [{channel:1},{channel:0},{channel:2},{channel:1},];

    // Callbacks //
    callback create_pipe();
    callback update_pipe(Pipe);
    callback enable_pipe(bool, int);
    callback remove_pipe(int);

    // PAGES //
    in-out property <int> page: 0;

    // Pipe List Page
    if page == 0: MainPage {
        pipelist <=> pipelist;

        set_page(p) => {page = p}
        // pipe related
        create_pipe => {
            create_pipe()
        }
        remove_pipe(pipe_idx) => {
            remove_pipe(pipe_idx)
        }

        update_pipe(new_pipe) => {
            update_pipe(new_pipe)
        }
        enable_pipe(enable, pipe_idx) => {
            enable_pipe(enable, pipe-idx)
        }
    }

    // Settings Page
    if page == 1: SettingsPage {
        set_page(p) => {page = p}
    }

    // uncomment vizualize pipelist
    /* 
    HorizontalBox {
        for i in pipelist: Text {
            text: (i.enabled? "enabled":"disabled") + i.channel;
        }
    }
    */
}
