import { AboutSlint, VerticalBox, Palette, CheckBox, Button, HorizontalBox, LineEdit, ComboBox } from "std-widgets.slint";
import { Pipe, Settings } from "../../../structs.slint";

export component Card inherits Rectangle
{
    in-out property <Settings> settings;

    in-out property <Pipe> pipe;
    in-out property <Pipe> edited_pipe: pipe;
    callback enable_pipe(bool, Pipe);
    callback update_pipe(Pipe, Pipe);
    callback remove_pipe(Pipe);

    property <bool> delete_dialog;
    
    height: self.min-height;
    background: Palette.control-background;

    border-radius: 8px;
    border-width: 1px;
    border-color: Palette.border;

    clip: true;

    HorizontalBox {
        VerticalBox {
            padding: 0;

            // Pipe Settings //
            HorizontalBox {
                padding: 0;

                CheckBox {
                    checked: pipe.enabled;
                    toggled => {
                        enable_pipe(self.checked, pipe);
                        edited_pipe.enabled = self.checked;
                    }
                }

                sink:= LineEdit {
                    text: pipe.sink;
                    enabled: edited_pipe.enabled;
                    changed text => {
                        edited_pipe.sink = self.text;
                    }
                }
                Text {
                    text: "→";
                    font-weight: 800;
                    vertical-alignment: center;
                }
                source:= LineEdit {
                    text: pipe.source;
                    enabled: edited_pipe.enabled;
                    changed text => {
                        edited_pipe.source = self.text;
                    }
                }

                ch:= ComboBox {
                    width: 120px;
                    model: ["Mono", "Stereo", "Surround"];
                    enabled: edited_pipe.enabled;
                    current-index: pipe.channel;
                    changed current-index => {
                        edited_pipe.channel = self.current-index;
                    }
                }
            }

            // Pipe Tasks //

            // If there are NO changes.
            if pipe == edited_pipe: HorizontalBox {
                padding: 0;

                TouchArea {
                    Text {
                        text: @tr("PipeCard@remove.btn");
                        color: parent.has-hover? #912: Palette.foreground;
                    }
                    clicked => {
                        // Opens the Delete dialog.
                        // See more below in the 'Delete dialog' section of this file.
                        if settings.confirm-to-delete-pipe {
                            delete_dialog = true;
                        } else {
                            remove_pipe(pipe)
                        }
                    }
                }

                Rectangle {}
            }

            // If there are ANY changes to apply or cancel.
            if pipe != edited_pipe: HorizontalBox {
                padding: 0;

                Text {
                    text: @tr("PipeCard@no-changes-until-apply.msg");
                    opacity: 0.25;
                }

                Rectangle {}

                // If it cancels, return the object to its original state.
                TouchArea {
                    Text {
                        text: @tr("PipeCard@cancel.btn");
                        color: parent.has-hover? Palette.accent-background: Palette.foreground;
                    }
                    clicked => {
                        edited_pipe = pipe;

                        sink.text = pipe.sink;
                        source.text = pipe.source;
                        ch.current-index = pipe.channel;
                    }
                }

                // If it applies, change the card object too.
                TouchArea {
                    Text {
                        text: @tr("PipeCard@apply.btn");
                        font-weight: 800;
                        color: parent.has-hover? Palette.accent-background: Palette.foreground;
                    }
                    clicked => {
                        update_pipe(pipe, edited_pipe);
                        edited_pipe = pipe;

                        sink.text = pipe.sink;
                        source.text = pipe.source;
                        ch.current-index = pipe.channel;
                    }
                }
            }
        }
    }

    // Delete Dialog //

    if delete_dialog: TouchArea{
        Rectangle {
            background: Palette.background.with-alpha(0.75);

            VerticalLayout {
                Rectangle {}

                HorizontalBox {
                    Rectangle {}
                    
                    Rectangle {
                        background: Palette.background;
                        border-radius: 4px;
                        Button {
                            text: @tr("PipeDeleteDialog@cancel.btn");
                            clicked => {
                                delete_dialog = false;
                            }
                        }
                    }

                    Rectangle {
                        background: #912;
                        border-radius: 4px;
                        Button {
                            text: @tr("PipeDeleteDialog@confirm.btn");
                            clicked => {
                                remove_pipe(pipe)
                            }
                        }
                    }
                }
                
                Rectangle {}
            }
        }
    }
}
