import { AboutSlint, VerticalBox, Button, ScrollView, Palette, HorizontalBox, ComboBox, CheckBox, LineEdit } from "std-widgets.slint";
import { Settings } from "../../structs.slint";

export component SettingsPage inherits VerticalLayout
{
    in-out property <Settings> settings;
    in-out property <Settings> new_settings: settings;

    callback set_page(int);
    callback apply_settings(Settings);

    // settings //
    HorizontalLayout {
        spacing: 0;
        ScrollView {
            VerticalBox {
                restore-on-system-startup:= CheckBox {
                    text: @tr("restore-on-system-startup-settings-option");
                    checked: settings.restore-on-system-startup;
                    toggled => {
                        new_settings.restore-on-system-startup = self.checked;
                    }
                }
                confirm-to-delete-pipe:= CheckBox {
                    text: @tr("confirm-to-delete-pipe-settings-option");
                    checked: settings.confirm-to-delete-pipe;
                    toggled => {
                        new_settings.confirm-to-delete-pipe = self.checked;
                    }
                }
            }
        }

        HorizontalBox {
            padding-left: 0;
            padding-right: 0;
            Rectangle {
                width: 1px;
                background: Palette.border;
            }
        }

        VerticalBox {
            width: 160px;
            spacing: 0;

            Text {
                text: "VirtualPipe 2.0.0 dev";
            }
            Text {
                text: "By Vinícius Adriel";
                opacity: 0.5;
            }
            
            Rectangle {}

            Image {
                height: 60px;
                source: @image-url("../../../../assets/images/MadeWithSlint.png");
            }
        }
    }

    // Footer //
    HorizontalBox {
        padding-top: 0;
        padding-bottom: 0;
        Rectangle {
            height: 1px;
            background: Palette.border;
        }
    }

    HorizontalBox {
        Button {
            text: @tr("apply-btn");
            enabled: settings != new_settings;
            clicked => {
                settings = new_settings;
                apply_settings(new_settings);
            }
        }
        Button {
            text: settings!= new_settings? @tr("undo-changes-btn") : @tr("go-back-btn");
            clicked => {
                if settings != new_settings {
                    new_settings = settings;

                    restore-on-system-startup.checked =
                        settings.restore-on-system-startup;
                    confirm-to-delete-pipe.checked =
                        settings.confirm-to-delete-pipe;
                } else {
                    set_page(0)
                }
            }
        }
        Rectangle {}
    }
}