import { AboutSlint, VerticalBox, Button, ScrollView, Palette, HorizontalBox } from "std-widgets.slint";
import { Card } from "components/Card.slint";

import { Pipe } from "../../structs.slint";

export component MainPage inherits VerticalLayout
{
    callback set_page(int);

    in-out property <[Pipe]> pipelist;
    callback create_pipe();
    callback remove_pipe(int);

    callback update_pipe(Pipe);
    callback enable_pipe(bool, int);

    ScrollView {
        VerticalBox {
            padding: 20px;
            spacing: 10px;
            for pipe in pipelist: Card {
                pipe: pipe;
                update_pipe(new_pipe) => {
                    pipe = new_pipe;
                    update_pipe(new_pipe);
                }
                enable_pipe(enable, idx) => {
                    pipe.enabled = enable;
                    enable_pipe(enable, idx);
                }
                remove_pipe(pipe_idx) => {
                    remove_pipe(pipe_idx)
                }
            }
        }
    }
    
    HorizontalBox {
        padding-top: 0;
        padding-bottom: 0;
        Rectangle {
            height: 1px;
            background: Palette.border;
        }
    }

    HorizontalBox {
        TouchArea {
            Text {
                text: "Help (F1)";
            }
        }
        Rectangle {}
        Button {
            text: "Settings";
            clicked => {
                set_page(1)
            }
        }
        Button {
            text: "Create new pipe";
            clicked => {
                create_pipe()
            }
        }
    }
    
}